# Base radio positions (x,y,z) starting with front-left and proceeding clockwise around vehicle (see below)
# [[x0,y0,z0],...,[xn,yn,zn]]

base_position: [[0.00,0.00,0.00], [0.05,-0.88,-0.11], [-2.20,-1.23,0.27], [-2.03,0.25,0.25]]

# Offset of base radio 0 from vehicle origin
base0_offset: [2.41,0.48,0.41]

# Base radio LOS start and finish angles (pi-radians) wrt x-axis (in front of vehicle) where the finish angle is clockwise from the start angle
# [[start0,finish0],...,[startn,finishn]]
base_los_angle: [[0.875,-0.4375],[0.4375,-0.875],[-0.167,0.625],[-0.625,0.167]]



#                            @
#                       x   @@@
#                          @@@@@
#                            @
#                            @
#                            @
#                            @
#           y    @           @
#              @@@           @
#             @@@@@@@@@@@@@@@@
#              @@@
#                @
#
#
#	   #,                                              #,      
#	  @ ##                                            @`+#     
#	 ,:  @                                           .;  @       
#	 ;.  @                                           :,  @     
#	 +::,@,,,,                                       ';:,@,,,,`
#	@:::::::::#                                     #:::::::::@
#	@         #                                     #         @
#	@         #                                     #         @
#	@         #                                     #         @
#	@    0    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    1    @
#	@         #                                     #         @
#	@         #                                     #         @
#	#@@@@@@@@@+                                     +@@@@@@@@@#
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	 ##@######                                     ######@##   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 ;;@;;;;;;                                     ;;;;;;@;;   
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@   
#	 @@@@@@@@@                                     @@@@@@@@@  
#	   @                                                 @     
#	   @                                                 @     
#	   @                                                 @     
#	   @                                               : @     
#	  @:@;                                            @:@@     
#	 ,:  @                                           .;  @      
#	 ;.  @                                           :,  @     
#	 '`  @                                           ;.  @     
#	@+++++++++#                                     #+++++++++@
#	@         #                                     #         @
#	@         #                                     #         @
#	@         #                                     #         @
#	@    3    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    2    @
#	@         #                                     #         @
#	@         #                                     #         @
#	@@@@@@@@@@#                                     #@@@@@@@@@@
