set(_CATKIN_CURRENT_PACKAGE "velodyne_ll")
set(velodyne_ll_VERSION "2.8.3")
set(velodyne_ll_MAINTAINER "Jon Petrosky <jonathan.d.petrosky.civ@mail.mil>")
set(velodyne_ll_PACKAGE_FORMAT "2")
set(velodyne_ll_BUILD_DEPENDS "message_generation" "geometry_msgs" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs" "tardec_msgs" "tf")
set(velodyne_ll_BUILD_EXPORT_DEPENDS "geometry_msgs" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs" "tardec_msgs" "tf")
set(velodyne_ll_BUILDTOOL_DEPENDS "catkin")
set(velodyne_ll_BUILDTOOL_EXPORT_DEPENDS )
set(velodyne_ll_EXEC_DEPENDS "message_runtime" "geometry_msgs" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs" "tardec_msgs" "tf")
set(velodyne_ll_RUN_DEPENDS "message_runtime" "geometry_msgs" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs" "tardec_msgs" "tf")
set(velodyne_ll_TEST_DEPENDS )
set(velodyne_ll_DOC_DEPENDS )
set(velodyne_ll_URL_WEBSITE "")
set(velodyne_ll_URL_BUGTRACKER "")
set(velodyne_ll_URL_REPOSITORY "git@dismount-git.datasys.swri.edu:tardec/tardec_drivers.git")
set(velodyne_ll_DEPRECATED "")