set(_CATKIN_CURRENT_PACKAGE "ay21_igvc")
set(ay21_igvc_VERSION "0.0.0")
set(ay21_igvc_MAINTAINER "Chloe DeWees <chloe.dewees@gmail.com>")
set(ay21_igvc_PACKAGE_FORMAT "2")
set(ay21_igvc_BUILD_DEPENDS "roslint" "message_generation" "roscpp" "rospy" "std_msgs" "sensor_msgs" "pacmod_msgs" "rosserial_arduino" "rosserial_client" "joy")
set(ay21_igvc_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "pacmod_msgs" "rosserial_arduino" "rosserial_client" "joy")
set(ay21_igvc_BUILDTOOL_DEPENDS "catkin")
set(ay21_igvc_BUILDTOOL_EXPORT_DEPENDS )
set(ay21_igvc_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "sensor_msgs" "pacmod_msgs" "rosserial_arduino" "rosserial_client" "joy")
set(ay21_igvc_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "sensor_msgs" "pacmod_msgs" "rosserial_arduino" "rosserial_client" "joy")
set(ay21_igvc_TEST_DEPENDS )
set(ay21_igvc_DOC_DEPENDS )
set(ay21_igvc_URL_WEBSITE "")
set(ay21_igvc_URL_BUGTRACKER "")
set(ay21_igvc_URL_REPOSITORY "")
set(ay21_igvc_DEPRECATED "")
